# Build and deploy to the Kubernetes staging namespace in the dev cluster

name: Staging - Build and Deploy on push

on:
  pull_request:
    types:
      - closed

defaults:
  run:
    shell: bash

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: mdb-dev
    steps:
      - uses: actions/checkout@v4
      - name: Pull MindsDB Github Actions
        uses: actions/checkout@v4
        with:
          repository: mindsdb/github-actions
          path: github-actions
      - uses: ./github-actions/build-push-ecr
        with:
          module-name: mindsdb-frontend
          build-for-environment: staging

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: mdb-dev
    needs: [build]
    strategy:
      matrix:
        environment: [staging, alpha-dev, dev]
    environment:
      name: ${{ matrix.environment }}
      url: ${{ vars.MINDSDB_ENV_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Pull MindsDB Github Actions
        uses: actions/checkout@v4
        with:
          repository: mindsdb/github-actions
          path: github-actions
      - uses: ./github-actions/setup-env
      - name: Notify of deployment starting
        id: slack
        uses: ./github-actions/slack-deploy-msg
        with:
          channel-id: ${{ secrets.SLACK_DEPLOYMENTS_CHANNEL_ID }}
          status: 'started'
          color: '#0099CC'
          env-name: ${{ matrix.environment }}
          env-url: ${{ vars.MINDSDB_ENV_URL }}
          slack-token: ${{ secrets.GH_ACTIONS_SLACK_BOT_TOKEN }}
      - uses: DevOps-Nirvana/aws-helm-multi-deploy-nodocker@v2
        with:
          environment-slug: '${{ matrix.environment }}'
          k8s-namespace: '${{ matrix.environment }}'
          image-tag: staging-${{ env.SLUG }}
          timeout: 600s
      - name: Notify of deployment finish
        uses: ./github-actions/slack-deploy-msg
        # Run this even if the deployment fails
        if: always()
        with:
          channel-id: ${{ secrets.SLACK_DEPLOYMENTS_CHANNEL_ID }}
          status: "${{ job.status == 'success' && 'finished' || 'failed' }}"
          color: "${{ job.status == 'success' && '#00C851' || '#FF4444' }}"
          env-name: ${{ matrix.environment }}
          env-url: ${{ vars.MINDSDB_ENV_URL }}
          slack-token: ${{ secrets.GH_ACTIONS_SLACK_BOT_TOKEN }}
          update-message-id: ${{ steps.slack.outputs.ts }}
